<a href="https://colab.research.google.com/github/arvind-maurya/MachineLearning/blob/master/Assignment/AIMLCEP_ARVIND_MAURYA_Q3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#First, we import the required packages
import torch
import numpy as np
import pandas as pd #the pandas library is useful for data processing 
import matplotlib.pyplot as plt #the matplotlib library is useful for plotting purposes


## **Q3.a Shuffle and break the data into 80% train and 20% test data**

In [ ]:
#Get the data from the csv file 
sample_data = pd.read_csv('https://github.com/arvind-maurya/MachineLearning/blob/master/Assignment/Q3/Q3_data.csv?raw=true', index_col=False)
#print the data 
sample_data

label  feature0  feature1  ...  feature781  feature782  feature783
0          1         0         0  ...           0           0           0
1          2         0         0  ...           0           0           0
2          3         0         0  ...           0           0           0
3          4         0         0  ...           0           0           0
4          1         0         0  ...           0           0           0
...      ...       ...       ...  ...         ...         ...         ...
23995      4         0         0  ...           0           0           0
23996      1         0         0  ...           0           0           0
23997      2         0         0  ...           0           0           0
23998      3         0         0  ...           0           0           0
23999      4         0         0  ...           0           0           0

[24000 rows x 785 columns]

In [ ]:
#Separate the feature and target column
y = sample_data.pop('label')
X = sample_data
print(X)
print(y)

       feature0  feature1  feature2  ...  feature781  feature782  feature783
0             0         0         0  ...           0           0           0
1             0         0         0  ...           0           0           0
2             0         0         0  ...           0           0           0
3             0         0         0  ...           0           0           0
4             0         0         0  ...           0           0           0
...         ...       ...       ...  ...         ...         ...         ...
23995         0         0         0  ...           0           0           0
23996         0         0         0  ...           0           0           0
23997         0         0         0  ...           0           0           0
23998         0         0         0  ...           0           0           0
23999         0         0         0  ...           0           0           0

[24000 rows x 784 columns]
0        1
1        2
2        3
3        4
4   

In [ ]:
#We will use the sklearn train_test_split which shuffle and break the data ins required ratio
from sklearn.model_selection import train_test_split
# split into train test sets
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.2)
print('Train data feature: ', X_train)
print('Train data Label: ', y_train)
print('Test data feature: ', X_test)
print('Test data Label: ',y_test)

Train data feature:         feature0  feature1  feature2  ...  feature781  feature782  feature783
21201         0         0         0  ...           0           0           0
19413         0         0         0  ...           0           0           0
17472         0         0         0  ...           0           0           0
3518          0         0         0  ...           0           0           0
20148         0         0         0  ...           0           0           0
...         ...       ...       ...  ...         ...         ...         ...
18051         0         0         0  ...           0           0           0
1710          0         0         0  ...           0           0           0
7489          0         0         0  ...           0           0           0
5094          0         0         0  ...           0           0           0
2088          0         0         0  ...           0           0           0

[19200 rows x 784 columns]
Train data Label:  21201   

In [ ]:
print('Shape of Train data feature: ', X_train.shape)
print('Shape of Train data Label: ', y_train.shape)
print('Shape of Test data feature: ', X_test.shape)
print('Shape of Test data Label: ',y_test.shape)

Shape of Train data feature:  (19200, 784)
Shape of Train data Label:  (19200,)
Shape of Test data feature:  (4800, 784)
Shape of Test data Label:  (4800,)


In [ ]:
#Get the unique lable from train and test feature and see if we dont have class imbalance in train and test data
unique, counts = np.unique(y_train, return_counts=True)
print('Train label:\n', np.asarray((unique, counts)).T)
unique, counts = np.unique(y_test, return_counts=True)
print('Test Label:\n',np.asarray((unique, counts)).T)

Train label:
 [[   1 4805]
 [   2 4837]
 [   3 4781]
 [   4 4777]]
Test Label:
 [[   1 1195]
 [   2 1163]
 [   3 1219]
 [   4 1223]]


## **Q3.b Train a multi-layer perceptron (MLP)**

Q3.b : [C, R] Use the train partition to train a multi-layer perceptron (MLP) with an input layer, 3
hidden layers and an output layer. You are free to choose the number of neurons and their ac-
tivation functions in the hidden layers. Use a soft-max at the output layer and a cross-entropy
loss function to perform classifcation. Describe the MLP architecture you have used. Using the
MLP model, report the accuracy, precision, recall, F1 score for the train set and test set.

In [ ]:
# from sklearn import preprocessing
# from keras.models import sequential #forward Propogation
# from keras.layers import Dense , Dropout, BatchNormalization #Dense is used for creating hidden and input layers
# from keras import optimizers # for back propogation
# #converting y response variable into categorical.
# from keras.utils.np_utils import to_categorical

import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
from keras.utils.np_utils import to_categorical
from sklearn.metrics import  classification_report , confusion_matrix , accuracy_score

In [ ]:
#Convert the label data into categorical data
y_train = to_categorical(y_train)
y_test = to_categorical(y_test)


In [ ]:
print('Shape of Train data feature: ', X_train.shape , 'type: ', type(X_train))
print('Shape of Train data Label: ', y_train.shape , 'type: ', type(y_train))
print('Shape of Test data feature: ', X_test.shape , 'type: ', type(X_test))
print('Shape of Test data Label: ',y_test.shape , 'type: ', type(y_test))
#Looking at the shape , we have 784 input and 5 output.


Shape of Train data feature:  (19200, 784) type:  <class 'pandas.core.frame.DataFrame'>
Shape of Train data Label:  (19200, 5) type:  <class 'numpy.ndarray'>
Shape of Test data feature:  (4800, 784) type:  <class 'pandas.core.frame.DataFrame'>
Shape of Test data Label:  (4800, 5) type:  <class 'numpy.ndarray'>


In [ ]:
#Create NN layers now
model = keras.Sequential()
model.add(layers.Dense(10,input_dim=784,activation='relu')) #i/p Layer
model.add(layers.Dense(8,input_dim=10,activation='relu')) # hidden layer1
model.add(layers.Dense(5,input_dim=8,activation='relu')) # hidden layer2
model.add(layers.Dense(5,input_dim=5,activation='relu')) # hidden layer3
model.add(layers.Dense(5,activation='softmax')) #output layer



In [ ]:
print(len(model.layers))  # 2

5


In [ ]:
#optimizer
adam = keras.optimizers.Adam(learning_rate = 0.001)
model.compile(optimizer=adam, loss='categorical_crossentropy', metrics=['accuracy'])

In [ ]:
#forward and back ward propogration
model.fit(X_train, y_train, batch_size=100, epochs=100)

Epoch 1/100
192/192 [==============================] - 1s 3ms/step - loss: 1.2567 - accuracy: 0.5805
Epoch 2/100
192/192 [==============================] - 1s 3ms/step - loss: 0.7349 - accuracy: 0.7656
Epoch 3/100
192/192 [==============================] - 1s 3ms/step - loss: 0.6495 - accuracy: 0.8216
Epoch 4/100
192/192 [==============================] - 1s 3ms/step - loss: 0.5817 - accuracy: 0.8567
Epoch 5/100
192/192 [==============================] - 1s 3ms/step - loss: 0.5230 - accuracy: 0.8817
Epoch 6/100
192/192 [==============================] - 1s 3ms/step - loss: 0.4697 - accuracy: 0.8936
Epoch 7/100
192/192 [==============================] - 1s 3ms/step - loss: 0.4181 - accuracy: 0.9053
Epoch 8/100
192/192 [==============================] - 1s 3ms/step - loss: 0.3641 - accuracy: 0.9142
Epoch 9/100
192/192 [==============================] - 1s 3ms/step - loss: 0.2803 - accuracy: 0.9301
Epoch 10/100
192/192 [==============================] - 1s 3ms/step - loss: 0.2090 - accura

In [ ]:
#predicted values
y_train_predict = model.predict(X_train)
y_train_predict

array([[0.0000000e+00, 1.7564156e-17, 9.9732745e-01, 4.2366202e-05,
        2.6301763e-03],
       [5.1556778e-15, 2.9009868e-06, 9.3258625e-01, 2.5525516e-02,
        4.1885324e-02],
       [2.1643721e-06, 9.9506879e-01, 1.0830968e-03, 3.6434131e-03,
        2.0254383e-04],
       ...,
       [1.6042807e-22, 2.5995964e-08, 9.7868860e-01, 1.5199176e-02,
        6.1122291e-03],
       [0.0000000e+00, 8.4313051e-08, 9.5515177e-02, 9.0448469e-01,
        2.1795541e-09],
       [2.1643721e-06, 9.9506879e-01, 1.0830968e-03, 3.6434131e-03,
        2.0254383e-04]], dtype=float32)

In [ ]:
y_test_predict = model.predict(X_test)
y_test_predict

array([[0.0000000e+00, 5.6910621e-20, 9.9645883e-01, 6.3882708e-06,
        3.5346993e-03],
       [1.6804893e-24, 7.2140009e-11, 9.7882026e-01, 1.6078887e-03,
        1.9571807e-02],
       [2.1643721e-06, 9.9506879e-01, 1.0830968e-03, 3.6434131e-03,
        2.0254383e-04],
       ...,
       [2.1643721e-06, 9.9506879e-01, 1.0830968e-03, 3.6434131e-03,
        2.0254383e-04],
       [0.0000000e+00, 4.3528108e-14, 8.5851289e-16, 1.0000000e+00,
        8.3065667e-15],
       [0.0000000e+00, 8.2708489e-09, 2.7903274e-01, 7.2096723e-01,
        1.2563809e-08]], dtype=float32)

In [ ]:
# make class predictions with the model
predictions = (model.predict(X_test) > 0.5).astype(int)
# summarize the first 5 cases
for i in range(5):
	print((X_test.iloc[i].tolist(), predictions[i], y_test[i]))

([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 191, 82, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 194, 250, 242, 93, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 199, 249, 88, 32, 13, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 228, 82, 11, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 51, 10, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 185, 20, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 255, 27, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 255, 27, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 255, 27, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 255, 27, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 255, 2

## **===========================================================**

3 (c) [C, R] Now consider that each data point represented in vector form can be represented as a
p  p matrix for a suitable p. Using this transformed train data, build a convolution neural
network (CNN) with 3 convolution cum max-pool blocks (where max-pool follows a convolu-
tion operation) followed by a fully connected layer and an output layer. You are free to choose
the kernel size, stride and padding in each convolution operation. Also use a max-pool layer
of appropriate grid size in each layer. Use a soft-max at the output layer and a cross-entropy
loss function to perform classification. Describe the CNN architecture you have used. Using the
CNN model, report the accuracy, precision, recall, F1 score for the train set and test set.

In [ ]:
#Imort the required libraries
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
from keras.utils.np_utils import to_categorical
from sklearn.metrics import  classification_report , confusion_matrix , accuracy_score

import matplotlib.pyplot as plt
import pandas as pd #the pandas library is useful for data processing 
import numpy as np
import random
import time

In [ ]:
#Get the data from the csv file 
sample_data_cnn = pd.read_csv('https://github.com/arvind-maurya/MachineLearning/blob/master/Assignment/Q3/Q3_data.csv?raw=true', index_col=False)
#print the data 
sample_data_cnn

label  feature0  feature1  ...  feature781  feature782  feature783
0          1         0         0  ...           0           0           0
1          2         0         0  ...           0           0           0
2          3         0         0  ...           0           0           0
3          4         0         0  ...           0           0           0
4          1         0         0  ...           0           0           0
...      ...       ...       ...  ...         ...         ...         ...
23995      4         0         0  ...           0           0           0
23996      1         0         0  ...           0           0           0
23997      2         0         0  ...           0           0           0
23998      3         0         0  ...           0           0           0
23999      4         0         0  ...           0           0           0

[24000 rows x 785 columns]

In [ ]:
#Separate the feature and target column
y_cnn = sample_data_cnn.pop('label')
X_cnn = sample_data_cnn
X_cnn = X_cnn.to_numpy()
y_cnn = y_cnn.to_numpy()
print(X_cnn)
print(y_cnn)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[1 2 3 ... 2 3 4]


In [ ]:
#We will use the sklearn train_test_split which shuffle and break the data ins required ratio
from sklearn.model_selection import train_test_split
# split into train test sets
X_train_cnn, X_test_cnn, y_train_cnn, y_test_cnn = train_test_split(X_cnn,y_cnn, test_size=0.2)
X_train_cnn = X_train_cnn/255
X_test_cnn = X_test_cnn/255
print('Train data feature: ', X_train_cnn)
print('Train data Label: ', y_train_cnn)
print('Test data feature: ', X_test_cnn)
print('Test data Label: ',y_test_cnn)

Train data feature:  [[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
Train data Label:  [3 2 4 ... 1 3 2]
Test data feature:  [[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
Test data Label:  [1 3 3 ... 1 4 2]


In [ ]:
print('Shape of Train data feature: ', X_train_cnn.shape)
print('Shape of Train data Label: ', y_train_cnn.shape)
print('Shape of Test data feature: ', X_test_cnn.shape)
print('Shape of Test data Label: ',y_test_cnn.shape)

Shape of Train data feature:  (19200, 784)
Shape of Train data Label:  (19200,)
Shape of Test data feature:  (4800, 784)
Shape of Test data Label:  (4800,)


In [ ]:
#Get the unique lable from train and test feature and see if we dont have class imbalance in train and test data
unique, counts = np.unique(y_train_cnn, return_counts=True)
print('Train label:\n', np.asarray((unique, counts)).T)
unique, counts = np.unique(y_test_cnn, return_counts=True)
print('Test Label:\n',np.asarray((unique, counts)).T)

Train label:
 [[   1 4796]
 [   2 4774]
 [   3 4775]
 [   4 4855]]
Test Label:
 [[   1 1204]
 [   2 1226]
 [   3 1225]
 [   4 1145]]


In [ ]:
#rehaping the images into equal dim.
X_train_cnn = X_train_cnn.reshape(len(X_train_cnn),28,28,1)
X_test_cnn = X_test_cnn.reshape(len(X_test_cnn),28,28,1)

In [ ]:
from keras.utils.np_utils import to_categorical
#one-hot encode target column
y_train_cnn = to_categorical(y_train_cnn)
y_test_cnn = to_categorical(y_test_cnn)
y_train_cnn[0]

array([0., 0., 0., 1., 0.], dtype=float32)

In [ ]:
#create model
model_cnn = keras.Sequential()
#add model layers
model_cnn.add(layers.Conv2D(64, kernel_size=3, activation='relu', input_shape=(28,28,1)))
model_cnn.add(layers.Conv2D(32, kernel_size=3, activation='relu'))
model_cnn.add(layers.Conv2D(16, kernel_size=3, activation='relu'))
model_cnn.add(layers.MaxPooling2D(pool_size=2))
model_cnn.add(layers.Flatten())
model_cnn.add(layers.Dense(5, activation='softmax'))

In [ ]:
#compile model using accuracy to measure model performance
model_cnn.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])


In [ ]:
#train the model
model_cnn.fit(X_train_cnn, y_train_cnn, validation_data=(X_test_cnn, y_test_cnn), epochs=3)

Epoch 1/3
600/600 [==============================] - 73s 121ms/step - loss: 0.1452 - accuracy: 0.9539 - val_loss: 0.0528 - val_accuracy: 0.9831
Epoch 2/3
600/600 [==============================] - 73s 121ms/step - loss: 0.0470 - accuracy: 0.9852 - val_loss: 0.0372 - val_accuracy: 0.9890
Epoch 3/3
600/600 [==============================] - 73s 121ms/step - loss: 0.0331 - accuracy: 0.9891 - val_loss: 0.0330 - val_accuracy: 0.9898


In [ ]:
#predict first 4 images in the test set
model_cnn.predict(X_test_cnn[:4])

array([[2.0807069e-12, 9.9970835e-01, 1.9939673e-08, 2.9163409e-04,
        1.4119780e-08],
       [1.1837005e-08, 1.2482560e-03, 4.3159227e-05, 9.9870002e-01,
        8.5385254e-06],
       [1.1150503e-12, 2.8192300e-09, 7.2564653e-05, 9.9992740e-01,
        1.0314193e-10],
       [5.3340117e-11, 3.7675107e-08, 9.9999118e-01, 2.7730810e-08,
        8.8615971e-06]], dtype=float32)

The above give the probability for prediction for classes. We should take the value which has higher probability 

In [ ]:
#actual results for first 4 images in test set
y_test_cnn[:4]

array([[0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 1., 0., 0.]], dtype=float32)

In [ ]:
score = model_cnn.evaluate(X_test_cnn, y_test_cnn, verbose = 0 )
print("Test Score: ", score[0])
print("Test accuracy: ", score[1])

Test Score:  0.032985761761665344
Test accuracy:  0.9897916913032532


Same  is matching with the test data output of test data.