<a href="https://colab.research.google.com/github/arvind-maurya/MachineLearning/blob/master/Assignment/AIMLCEP_Q3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
#First, we import the required packages
import torch
import numpy as np
import pandas as pd #the pandas library is useful for data processing 
import matplotlib.pyplot as plt #the matplotlib library is useful for plotting purposes


## **Q3.a Shuffle and break the data into 80% train and 20% test data**

In [3]:


#Get the data from the csv file 
sample_data = pd.read_csv('https://github.com/arvind-maurya/MachineLearning/blob/master/Assignment/Q3/Q3_data.csv?raw=true', index_col=False)


#print the data 
sample_data

label  feature0  feature1  ...  feature781  feature782  feature783
0          1         0         0  ...           0           0           0
1          2         0         0  ...           0           0           0
2          3         0         0  ...           0           0           0
3          4         0         0  ...           0           0           0
4          1         0         0  ...           0           0           0
...      ...       ...       ...  ...         ...         ...         ...
23995      4         0         0  ...           0           0           0
23996      1         0         0  ...           0           0           0
23997      2         0         0  ...           0           0           0
23998      3         0         0  ...           0           0           0
23999      4         0         0  ...           0           0           0

[24000 rows x 785 columns]

In [4]:
#Separate the feature and target column
y = sample_data.pop('label')
X = sample_data
print(X)
print(y)

       feature0  feature1  feature2  ...  feature781  feature782  feature783
0             0         0         0  ...           0           0           0
1             0         0         0  ...           0           0           0
2             0         0         0  ...           0           0           0
3             0         0         0  ...           0           0           0
4             0         0         0  ...           0           0           0
...         ...       ...       ...  ...         ...         ...         ...
23995         0         0         0  ...           0           0           0
23996         0         0         0  ...           0           0           0
23997         0         0         0  ...           0           0           0
23998         0         0         0  ...           0           0           0
23999         0         0         0  ...           0           0           0

[24000 rows x 784 columns]
0        1
1        2
2        3
3        4
4   

In [5]:
#We will use the sklearn train_test_split which shuffle and break the data ins required ratio
from sklearn.model_selection import train_test_split
# split into train test sets
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.2)
print('Train data feature: ', X_train)
print('Train data Label: ', y_train)
print('Test data feature: ', X_test)
print('Test data Label: ',y_test)

Train data feature:         feature0  feature1  feature2  ...  feature781  feature782  feature783
7597          0         0         0  ...           0           0           0
5219          0         0         0  ...           0           0           0
22885         0         0         0  ...           0           0           0
22590         0         0         0  ...           0           0           0
4347          0         0         0  ...           0           0           0
...         ...       ...       ...  ...         ...         ...         ...
8761          0         0         0  ...           0           0           0
1007          0         0         0  ...           0           0           0
16797         0         0         0  ...           0           0           0
9869          0         0         0  ...           0           0           0
4070          0         0         0  ...           0           0           0

[19200 rows x 784 columns]
Train data Label:  7597    

In [6]:
print('Shape of Train data feature: ', X_train.shape)
print('Shape of Train data Label: ', y_train.shape)
print('Shape of Test data feature: ', X_test.shape)
print('Shape of Test data Label: ',y_test.shape)

Shape of Train data feature:  (19200, 784)
Shape of Train data Label:  (19200,)
Shape of Test data feature:  (4800, 784)
Shape of Test data Label:  (4800,)


In [7]:
#Get the unique lable from train and test feature and see if we dont have class imbalance in train and test data
unique, counts = np.unique(y_train, return_counts=True)
print('Train label:\n', np.asarray((unique, counts)).T)
unique, counts = np.unique(y_test, return_counts=True)
print('Test Label:\n',np.asarray((unique, counts)).T)

Train label:
 [[   1 4821]
 [   2 4770]
 [   3 4792]
 [   4 4817]]
Test Label:
 [[   1 1179]
 [   2 1230]
 [   3 1208]
 [   4 1183]]


## **Q3.b Train a multi-layer perceptron (MLP)**

Q3.b : [C, R] Use the train partition to train a multi-layer perceptron (MLP) with an input layer, 3
hidden layers and an output layer. You are free to choose the number of neurons and their ac-
tivation functions in the hidden layers. Use a soft-max at the output layer and a cross-entropy
loss function to perform classifcation. Describe the MLP architecture you have used. Using the
MLP model, report the accuracy, precision, recall, F1 score for the train set and test set.

In [60]:
# from sklearn import preprocessing
# from keras.models import sequential #forward Propogation
# from keras.layers import Dense , Dropout, BatchNormalization #Dense is used for creating hidden and input layers
# from keras import optimizers # for back propogation
# #converting y response variable into categorical.
# from keras.utils.np_utils import to_categorical

import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
from keras.utils.np_utils import to_categorical
from sklearn.metrics import  classification_report , confusion_matrix , accuracy_score

In [9]:
#Convert the label data into categorical data
y_train = to_categorical(y_train)
y_test = to_categorical(y_test)


In [59]:
y_train

array([[0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 1., 0., 0.],
       ...,
       [0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.]], dtype=float32)

In [48]:
print('Shape of Train data feature: ', X_train.shape , 'type: ', type(X_train))
print('Shape of Train data Label: ', y_train.shape , 'type: ', type(y_train))
print('Shape of Test data feature: ', X_test.shape , 'type: ', type(X_test))
print('Shape of Test data Label: ',y_test.shape , 'type: ', type(y_test))
#Looking at the shape , we have 784 input and 5 output.


Shape of Train data feature:  (19200, 784) type:  <class 'pandas.core.frame.DataFrame'>
Shape of Train data Label:  (19200, 5) type:  <class 'numpy.ndarray'>
Shape of Test data feature:  (4800, 784) type:  <class 'pandas.core.frame.DataFrame'>
Shape of Test data Label:  (4800, 5) type:  <class 'numpy.ndarray'>


In [63]:
#Create NN layers now
model = keras.Sequential()
model.add(layers.Dense(10,input_dim=784,activation='relu')) #i/p Layer
model.add(layers.Dense(8,input_dim=10,activation='relu')) # hidden layer1
model.add(layers.Dense(5,input_dim=8,activation='relu')) # hidden layer2
model.add(layers.Dense(5,input_dim=5,activation='relu')) # hidden layer3
model.add(layers.Dense(5,activation='softmax')) #output layer



In [56]:
print(len(model.layers))  # 2

5


In [64]:
#optimizer
adam = keras.optimizers.Adam(learning_rate = 0.001)
model.compile(optimizer=adam, loss='categorical_crossentropy', metrics=['accuracy'])

In [66]:
#forward and back ward propogration
model.fit(X_train, y_train, batch_size=100, epochs=100)

Epoch 1/100
192/192 [==============================] - 0s 2ms/step - loss: 0.0422 - accuracy: 0.9872
Epoch 2/100
192/192 [==============================] - 0s 2ms/step - loss: 0.0410 - accuracy: 0.9876
Epoch 3/100
192/192 [==============================] - 0s 2ms/step - loss: 0.0398 - accuracy: 0.9882
Epoch 4/100
192/192 [==============================] - 0s 2ms/step - loss: 0.0405 - accuracy: 0.9883
Epoch 5/100
192/192 [==============================] - 0s 2ms/step - loss: 0.0380 - accuracy: 0.9892
Epoch 6/100
192/192 [==============================] - 0s 2ms/step - loss: 0.0407 - accuracy: 0.9882
Epoch 7/100
192/192 [==============================] - 0s 2ms/step - loss: 0.0336 - accuracy: 0.9893
Epoch 8/100
192/192 [==============================] - 0s 2ms/step - loss: 0.0355 - accuracy: 0.9889
Epoch 9/100
192/192 [==============================] - 0s 2ms/step - loss: 0.0340 - accuracy: 0.9892
Epoch 10/100
192/192 [==============================] - 0s 2ms/step - loss: 0.0352 - accura

In [67]:
#predicted values
y_train_predict = model.predict(X_train)
y_train_predict

array([[6.4881380e-18, 3.1414251e-07, 9.9987519e-01, 1.2062728e-04,
        3.8306034e-06],
       [0.0000000e+00, 4.2950279e-12, 1.2797260e-13, 0.0000000e+00,
        1.0000000e+00],
       [0.0000000e+00, 0.0000000e+00, 1.0000000e+00, 2.0216018e-33,
        0.0000000e+00],
       ...,
       [0.0000000e+00, 0.0000000e+00, 1.0000000e+00, 3.0932704e-33,
        0.0000000e+00],
       [8.6637703e-26, 1.5669402e-10, 9.9999881e-01, 1.2161901e-06,
        1.9796481e-08],
       [0.0000000e+00, 1.8382172e-13, 4.1805447e-25, 1.0000000e+00,
        1.3208991e-30]], dtype=float32)

In [68]:
y_test_predict = model.predict(X_test)
y_test_predict

array([[0.0000000e+00, 1.3298673e-07, 1.5162297e-12, 9.9999988e-01,
        1.7677806e-15],
       [0.0000000e+00, 5.7325173e-30, 4.7951675e-36, 0.0000000e+00,
        1.0000000e+00],
       [3.5663539e-30, 7.6539276e-05, 1.2501791e-06, 9.9992216e-01,
        2.3596536e-08],
       ...,
       [7.0090878e-11, 1.6155697e-02, 5.7618525e-02, 9.2098051e-01,
        5.2453219e-03],
       [1.2057896e-18, 1.2022267e-03, 4.5876956e-04, 9.9831009e-01,
        2.8959697e-05],
       [3.7400551e-12, 1.9560177e-05, 9.9770182e-01, 2.0494552e-03,
        2.2915877e-04]], dtype=float32)

In [73]:
# make class predictions with the model
predictions = (model.predict(X_test) > 0.5).astype(int)
# summarize the first 5 cases
for i in range(5):
	print((X_test.iloc[i].tolist(), predictions[i], y_test[i]))

([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 217, 255, 255, 82, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 217, 255, 255, 242, 90, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 217, 78, 32, 183, 97, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 38, 9, 0, 172, 227, 93, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 39, 179, 112, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 157, 112, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 157, 112, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 108, 218, 112, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 172, 164, 48, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 

## **===========================================================**

3 (c) [C, R] Now consider that each data point represented in vector form can be represented as a
p  p matrix for a suitable p. Using this transformed train data, build a convolution neural
network (CNN) with 3 convolution cum max-pool blocks (where max-pool follows a convolu-
tion operation) followed by a fully connected layer and an output layer. You are free to choose
the kernel size, stride and padding in each convolution operation. Also use a max-pool layer
of appropriate grid size in each layer. Use a soft-max at the output layer and a cross-entropy
loss function to perform classification. Describe the CNN architecture you have used. Using the
CNN model, report the accuracy, precision, recall, F1 score for the train set and test set.

In [47]:
X_train_cnn = X_train.copy()
X_train_cnn = X_train_cnn.to_numpy()
X_test_cnn = X_test.copy()
X_test_cnn = X_test_cnn.to_numpy()
y_train_cnn = y_train.copy()
type(y_train_cnn)
y_test_cnn = y_test.copy()

type(y_test_cnn)


numpy.ndarray

In [50]:
print('Shape of Train data feature: ', X_train_cnn.shape , 'type: ', type(X_train_cnn))
print('Shape of Train data Label: ', y_train_cnn.shape , 'type: ', type(y_train_cnn))
print('Shape of Test data feature: ', X_test_cnn.shape , 'type: ', type(X_test_cnn))
print('Shape of Test data Label: ',y_test_cnn.shape , 'type: ', type(y_test_cnn))
#Looking at the shape , we have 784 input and 5 output.

Shape of Train data feature:  (19200, 784) type:  <class 'numpy.ndarray'>
Shape of Train data Label:  (19200, 5) type:  <class 'numpy.ndarray'>
Shape of Test data feature:  (4800, 784) type:  <class 'numpy.ndarray'>
Shape of Test data Label:  (4800, 5) type:  <class 'numpy.ndarray'>
