<a href="https://colab.research.google.com/github/arvind-maurya/MachineLearning/blob/master/Assignment/AIMLCEP_Q3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#First, we import the required packages
import torch
import numpy as np
import pandas as pd #the pandas library is useful for data processing 
import matplotlib.pyplot as plt #the matplotlib library is useful for plotting purposes


## **Q3.a Shuffle and break the data into 80% train and 20% test data**

In [2]:


#Get the data from the csv file 
sample_data = pd.read_csv('https://github.com/arvind-maurya/MachineLearning/blob/master/Assignment/Q3/Q3_data.csv?raw=true', index_col=False)


#print the data 
sample_data

label  feature0  feature1  ...  feature781  feature782  feature783
0          1         0         0  ...           0           0           0
1          2         0         0  ...           0           0           0
2          3         0         0  ...           0           0           0
3          4         0         0  ...           0           0           0
4          1         0         0  ...           0           0           0
...      ...       ...       ...  ...         ...         ...         ...
23995      4         0         0  ...           0           0           0
23996      1         0         0  ...           0           0           0
23997      2         0         0  ...           0           0           0
23998      3         0         0  ...           0           0           0
23999      4         0         0  ...           0           0           0

[24000 rows x 785 columns]

In [3]:
#Separate the feature and target column
y = sample_data.pop('label')
X = sample_data
print(X)
print(y)

       feature0  feature1  feature2  ...  feature781  feature782  feature783
0             0         0         0  ...           0           0           0
1             0         0         0  ...           0           0           0
2             0         0         0  ...           0           0           0
3             0         0         0  ...           0           0           0
4             0         0         0  ...           0           0           0
...         ...       ...       ...  ...         ...         ...         ...
23995         0         0         0  ...           0           0           0
23996         0         0         0  ...           0           0           0
23997         0         0         0  ...           0           0           0
23998         0         0         0  ...           0           0           0
23999         0         0         0  ...           0           0           0

[24000 rows x 784 columns]
0        1
1        2
2        3
3        4
4   

In [4]:
#We will use the sklearn train_test_split which shuffle and break the data ins required ratio
from sklearn.model_selection import train_test_split
# split into train test sets
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.2)
print('Train data feature: ', X_train)
print('Train data Label: ', y_train)
print('Test data feature: ', X_test)
print('Test data Label: ',y_test)

Train data feature:         feature0  feature1  feature2  ...  feature781  feature782  feature783
12930         0         0         0  ...           0           0           0
19054         0         0         0  ...           0           0           0
6705          0         0         0  ...           0           0           0
14608         0         0         0  ...           0           0           0
16460         0         0         0  ...           0           0           0
...         ...       ...       ...  ...         ...         ...         ...
12972         0         0         0  ...           0           0           0
20114         0         0         0  ...           0           0           0
927           0         0         0  ...           0           0           0
11326         0         0         0  ...           0           0           0
1296          0         0         0  ...           0           0           0

[19200 rows x 784 columns]
Train data Label:  12930   

In [5]:
print('Shape of Train data feature: ', X_train.shape)
print('Shape of Train data Label: ', y_train.shape)
print('Shape of Test data feature: ', X_test.shape)
print('Shape of Test data Label: ',y_test.shape)

Shape of Train data feature:  (19200, 784)
Shape of Train data Label:  (19200,)
Shape of Test data feature:  (4800, 784)
Shape of Test data Label:  (4800,)


In [6]:
#Get the unique lable from train and test feature and see if we dont have class imbalance in train and test data
unique, counts = np.unique(y_train, return_counts=True)
print('Train label:\n', np.asarray((unique, counts)).T)
unique, counts = np.unique(y_test, return_counts=True)
print('Test Label:\n',np.asarray((unique, counts)).T)

Train label:
 [[   1 4767]
 [   2 4821]
 [   3 4782]
 [   4 4830]]
Test Label:
 [[   1 1233]
 [   2 1179]
 [   3 1218]
 [   4 1170]]


## **Q3.b Train a multi-layer perceptron (MLP)**

Q3.b : [C, R] Use the train partition to train a multi-layer perceptron (MLP) with an input layer, 3
hidden layers and an output layer. You are free to choose the number of neurons and their ac-
tivation functions in the hidden layers. Use a soft-max at the output layer and a cross-entropy
loss function to perform classifcation. Describe the MLP architecture you have used. Using the
MLP model, report the accuracy, precision, recall, F1 score for the train set and test set.

In [7]:
# from sklearn import preprocessing
# from keras.models import sequential #forward Propogation
# from keras.layers import Dense , Dropout, BatchNormalization #Dense is used for creating hidden and input layers
# from keras import optimizers # for back propogation
# #converting y response variable into categorical.
# from keras.utils.np_utils import to_categorical

import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
from keras.utils.np_utils import to_categorical
from sklearn.metrics import  classification_report , confusion_matrix , accuracy_score

In [9]:
#Convert the label data into categorical data
y_train = to_categorical(y_train)
y_test = to_categorical(y_test)


In [10]:
print('Shape of Train data feature: ', X_train.shape)
print('Shape of Train data Label: ', y_train.shape)
print('Shape of Test data feature: ', X_test.shape)
print('Shape of Test data Label: ',y_test.shape)
#Looking at the shape , we have 784 input and 5 output.


Shape of Train data feature:  (19200, 784)
Shape of Train data Label:  (19200, 5)
Shape of Test data feature:  (4800, 784)
Shape of Test data Label:  (4800, 5)


In [42]:
#Create NN layers now
model = keras.Sequential()
model.add(layers.Dense(10,input_dim=784,activation='relu')) #i/p Layer
model.add(layers.Dense(8,input_dim=10,activation='relu')) # hidden layer1
model.add(layers.Dense(5,input_dim=8,activation='relu')) # hidden layer2
model.add(layers.Dense(5,input_dim=5,activation='relu')) # hidden layer3
model.add(layers.Dense(5,activation='softmax')) #output layer



In [43]:
print(len(model.layers))  # 2

5


In [55]:
#optimizer
adam = keras.optimizers.Adam(learning_rate = 0.001)
model.compile(optimizer=adam, loss='categorical_crossentropy', metrics=['accuracy'])

In [62]:
#forward and back ward propogration
model.fit(X_train, y_train, batch_size=100, epochs=50)

Epoch 1/50
192/192 [==============================] - 1s 4ms/step - loss: 0.0124 - accuracy: 0.9966
Epoch 2/50
192/192 [==============================] - 1s 4ms/step - loss: 0.0119 - accuracy: 0.9966
Epoch 3/50
192/192 [==============================] - 1s 4ms/step - loss: 0.0113 - accuracy: 0.9968
Epoch 4/50
192/192 [==============================] - 1s 4ms/step - loss: 0.0112 - accuracy: 0.9968
Epoch 5/50
192/192 [==============================] - 1s 4ms/step - loss: 0.0110 - accuracy: 0.9968
Epoch 6/50
192/192 [==============================] - 1s 4ms/step - loss: 0.0112 - accuracy: 0.9969
Epoch 7/50
192/192 [==============================] - 1s 4ms/step - loss: 0.0110 - accuracy: 0.9970
Epoch 8/50
192/192 [==============================] - 1s 4ms/step - loss: 0.0110 - accuracy: 0.9969
Epoch 9/50
192/192 [==============================] - 1s 4ms/step - loss: 0.0108 - accuracy: 0.9971
Epoch 10/50
192/192 [==============================] - 1s 4ms/step - loss: 0.0106 - accuracy: 0.9972

In [48]:
#predicted values
y_train_predict = model.predict(X_train)
y_train_predict

array([[0.0000000e+00, 9.8293211e-05, 3.3981763e-07, 9.9990141e-01,
        1.0006586e-08],
       [0.0000000e+00, 1.1426476e-06, 9.8816389e-12, 9.9999881e-01,
        8.3923015e-14],
       [2.3407037e-07, 9.9346433e-03, 9.0328246e-01, 5.4951549e-02,
        3.1831205e-02],
       ...,
       [0.0000000e+00, 2.9162959e-05, 1.0171284e-23, 9.1430439e-07,
        9.9996996e-01],
       [5.8409288e-36, 5.0921639e-04, 1.6091693e-05, 9.9947399e-01,
        7.5004408e-07],
       [0.0000000e+00, 9.9999893e-01, 2.0374834e-21, 1.0990456e-06,
        1.5860783e-15]], dtype=float32)

In [49]:
y_test_predict = model.predict(X_test)
y_test_predict

array([[0.0000000e+00, 1.4456177e-10, 1.0000000e+00, 1.0861074e-14,
        1.8259495e-38],
       [0.0000000e+00, 9.9980503e-01, 1.1261595e-13, 1.9494042e-04,
        1.7993534e-10],
       [0.0000000e+00, 1.3339679e-06, 1.4206291e-11, 9.9999869e-01,
        1.2597903e-13],
       ...,
       [0.0000000e+00, 2.1059347e-04, 2.0289478e-06, 9.9978727e-01,
        7.3907664e-08],
       [7.4971325e-29, 1.7065256e-03, 2.7478841e-04, 9.9800068e-01,
        1.7957920e-05],
       [5.1827270e-34, 7.0943328e-04, 3.5027493e-05, 9.9925369e-01,
        1.7910836e-06]], dtype=float32)

## **===========================================================**

3 (c) [C, R] Now consider that each data point represented in vector form can be represented as a
p  p matrix for a suitable p. Using this transformed train data, build a convolution neural
network (CNN) with 3 convolution cum max-pool blocks (where max-pool follows a convolu-
tion operation) followed by a fully connected layer and an output layer. You are free to choose
the kernel size, stride and padding in each convolution operation. Also use a max-pool layer
of appropriate grid size in each layer. Use a soft-max at the output layer and a cross-entropy
loss function to perform classification. Describe the CNN architecture you have used. Using the
CNN model, report the accuracy, precision, recall, F1 score for the train set and test set.