<a href="https://colab.research.google.com/github/arvind-maurya/MachineLearning/blob/master/Assignment/AIMLCEP_Q3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#First, we import the required packages
import torch
import numpy as np
import pandas as pd #the pandas library is useful for data processing 
import matplotlib.pyplot as plt #the matplotlib library is useful for plotting purposes


## **Q3.a Shuffle and break the data into 80% train and 20% test data**

In [2]:
#Get the data from the csv file 
sample_data = pd.read_csv('https://github.com/arvind-maurya/MachineLearning/blob/master/Assignment/Q3/Q3_data.csv?raw=true', index_col=False)
#print the data 
sample_data

label  feature0  feature1  ...  feature781  feature782  feature783
0          1         0         0  ...           0           0           0
1          2         0         0  ...           0           0           0
2          3         0         0  ...           0           0           0
3          4         0         0  ...           0           0           0
4          1         0         0  ...           0           0           0
...      ...       ...       ...  ...         ...         ...         ...
23995      4         0         0  ...           0           0           0
23996      1         0         0  ...           0           0           0
23997      2         0         0  ...           0           0           0
23998      3         0         0  ...           0           0           0
23999      4         0         0  ...           0           0           0

[24000 rows x 785 columns]

In [3]:
#Separate the feature and target column
y = sample_data.pop('label')
X = sample_data
print(X)
print(y)

       feature0  feature1  feature2  ...  feature781  feature782  feature783
0             0         0         0  ...           0           0           0
1             0         0         0  ...           0           0           0
2             0         0         0  ...           0           0           0
3             0         0         0  ...           0           0           0
4             0         0         0  ...           0           0           0
...         ...       ...       ...  ...         ...         ...         ...
23995         0         0         0  ...           0           0           0
23996         0         0         0  ...           0           0           0
23997         0         0         0  ...           0           0           0
23998         0         0         0  ...           0           0           0
23999         0         0         0  ...           0           0           0

[24000 rows x 784 columns]
0        1
1        2
2        3
3        4
4   

In [4]:
#We will use the sklearn train_test_split which shuffle and break the data ins required ratio
from sklearn.model_selection import train_test_split
# split into train test sets
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.2)
print('Train data feature: ', X_train)
print('Train data Label: ', y_train)
print('Test data feature: ', X_test)
print('Test data Label: ',y_test)

Train data feature:         feature0  feature1  feature2  ...  feature781  feature782  feature783
19901         0         0         0  ...           0           0           0
6976          0         0         0  ...           0           0           0
23652         0         0         0  ...           0           0           0
20638         0         0         0  ...           0           0           0
14071         0         0         0  ...           0           0           0
...         ...       ...       ...  ...         ...         ...         ...
10319         0         0         0  ...           0           0           0
520           0         0         0  ...           0           0           0
10400         0         0         0  ...           0           0           0
22945         0         0         0  ...           0           0           0
16522         0         0         0  ...           0           0           0

[19200 rows x 784 columns]
Train data Label:  19901   

In [5]:
print('Shape of Train data feature: ', X_train.shape)
print('Shape of Train data Label: ', y_train.shape)
print('Shape of Test data feature: ', X_test.shape)
print('Shape of Test data Label: ',y_test.shape)

Shape of Train data feature:  (19200, 784)
Shape of Train data Label:  (19200,)
Shape of Test data feature:  (4800, 784)
Shape of Test data Label:  (4800,)


In [6]:
#Get the unique lable from train and test feature and see if we dont have class imbalance in train and test data
unique, counts = np.unique(y_train, return_counts=True)
print('Train label:\n', np.asarray((unique, counts)).T)
unique, counts = np.unique(y_test, return_counts=True)
print('Test Label:\n',np.asarray((unique, counts)).T)

Train label:
 [[   1 4796]
 [   2 4791]
 [   3 4768]
 [   4 4845]]
Test Label:
 [[   1 1204]
 [   2 1209]
 [   3 1232]
 [   4 1155]]


## **Q3.b Train a multi-layer perceptron (MLP)**

Q3.b : [C, R] Use the train partition to train a multi-layer perceptron (MLP) with an input layer, 3
hidden layers and an output layer. You are free to choose the number of neurons and their ac-
tivation functions in the hidden layers. Use a soft-max at the output layer and a cross-entropy
loss function to perform classifcation. Describe the MLP architecture you have used. Using the
MLP model, report the accuracy, precision, recall, F1 score for the train set and test set.

In [7]:
# from sklearn import preprocessing
# from keras.models import sequential #forward Propogation
# from keras.layers import Dense , Dropout, BatchNormalization #Dense is used for creating hidden and input layers
# from keras import optimizers # for back propogation
# #converting y response variable into categorical.
# from keras.utils.np_utils import to_categorical

import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
from keras.utils.np_utils import to_categorical
from sklearn.metrics import  classification_report , confusion_matrix , accuracy_score

In [8]:
#Convert the label data into categorical data
y_train = to_categorical(y_train)
y_test = to_categorical(y_test)


In [9]:
print('Shape of Train data feature: ', X_train.shape , 'type: ', type(X_train))
print('Shape of Train data Label: ', y_train.shape , 'type: ', type(y_train))
print('Shape of Test data feature: ', X_test.shape , 'type: ', type(X_test))
print('Shape of Test data Label: ',y_test.shape , 'type: ', type(y_test))
#Looking at the shape , we have 784 input and 5 output.


Shape of Train data feature:  (19200, 784) type:  <class 'pandas.core.frame.DataFrame'>
Shape of Train data Label:  (19200, 5) type:  <class 'numpy.ndarray'>
Shape of Test data feature:  (4800, 784) type:  <class 'pandas.core.frame.DataFrame'>
Shape of Test data Label:  (4800, 5) type:  <class 'numpy.ndarray'>


In [10]:
#Create NN layers now
model = keras.Sequential()
model.add(layers.Dense(10,input_dim=784,activation='relu')) #i/p Layer
model.add(layers.Dense(8,input_dim=10,activation='relu')) # hidden layer1
model.add(layers.Dense(5,input_dim=8,activation='relu')) # hidden layer2
model.add(layers.Dense(5,input_dim=5,activation='relu')) # hidden layer3
model.add(layers.Dense(5,activation='softmax')) #output layer



In [11]:
print(len(model.layers))  # 2

5


In [12]:
#optimizer
adam = keras.optimizers.Adam(learning_rate = 0.001)
model.compile(optimizer=adam, loss='categorical_crossentropy', metrics=['accuracy'])

In [13]:
#forward and back ward propogration
model.fit(X_train, y_train, batch_size=100, epochs=100)

Epoch 1/100
192/192 [==============================] - 1s 2ms/step - loss: 1.1720 - accuracy: 0.4785
Epoch 2/100
192/192 [==============================] - 1s 3ms/step - loss: 0.6794 - accuracy: 0.6755
Epoch 3/100
192/192 [==============================] - 0s 2ms/step - loss: 0.4858 - accuracy: 0.8210
Epoch 4/100
192/192 [==============================] - 0s 2ms/step - loss: 0.3095 - accuracy: 0.9249
Epoch 5/100
192/192 [==============================] - 0s 2ms/step - loss: 0.1787 - accuracy: 0.9464
Epoch 6/100
192/192 [==============================] - 0s 2ms/step - loss: 0.1558 - accuracy: 0.9533
Epoch 7/100
192/192 [==============================] - 0s 2ms/step - loss: 0.1410 - accuracy: 0.9561
Epoch 8/100
192/192 [==============================] - 0s 2ms/step - loss: 0.1317 - accuracy: 0.9590
Epoch 9/100
192/192 [==============================] - 0s 2ms/step - loss: 0.1204 - accuracy: 0.9628
Epoch 10/100
192/192 [==============================] - 0s 2ms/step - loss: 0.1126 - accura

In [14]:
#predicted values
y_train_predict = model.predict(X_train)
y_train_predict

array([[0.0000000e+00, 7.0272839e-15, 9.9913615e-01, 8.6372293e-04,
        7.2867444e-08],
       [0.0000000e+00, 1.0000000e+00, 2.0145588e-17, 1.7973002e-13,
        1.1708965e-12],
       [0.0000000e+00, 1.0000000e+00, 8.8548823e-23, 9.9093259e-22,
        7.1592949e-13],
       ...,
       [0.0000000e+00, 1.0000000e+00, 8.3075170e-15, 1.9091797e-14,
        1.3613374e-08],
       [0.0000000e+00, 8.6253332e-18, 9.9916506e-01, 8.3499326e-04,
        1.2239122e-09],
       [0.0000000e+00, 5.1141160e-21, 4.7728240e-31, 1.0000000e+00,
        5.5432891e-25]], dtype=float32)

In [15]:
y_test_predict = model.predict(X_test)
y_test_predict

array([[0.0000000e+00, 1.0000000e+00, 5.2041480e-15, 2.0905420e-14,
        7.0287411e-09],
       [2.6334106e-34, 5.2645106e-07, 1.7459504e-05, 9.9998200e-01,
        1.6708558e-10],
       [0.0000000e+00, 1.0000000e+00, 7.6103349e-14, 1.5761779e-13,
        4.1723759e-08],
       ...,
       [0.0000000e+00, 1.8935872e-16, 2.4194151e-15, 1.0000000e+00,
        1.7617979e-28],
       [0.0000000e+00, 1.0000000e+00, 2.9612650e-16, 1.2207049e-15,
        1.7978867e-09],
       [0.0000000e+00, 2.1725211e-19, 7.3844831e-32, 1.0000000e+00,
        5.0969055e-26]], dtype=float32)

In [16]:
# make class predictions with the model
predictions = (model.predict(X_test) > 0.5).astype(int)
# summarize the first 5 cases
for i in range(5):
	print((X_test.iloc[i].tolist(), predictions[i], y_test[i]))

([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 191, 253, 141, 0, 0, 191, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 52, 220, 133, 0, 0, 0, 191, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 115, 112, 0, 0, 0, 0, 191, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 115, 64, 0, 0, 0, 0, 191, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 115, 64, 0, 0, 0, 0, 191, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 115, 188, 0, 0, 0, 0, 191, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 6, 13, 0, 0, 0, 0, 191, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 242, 143, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 

## **===========================================================**

3 (c) [C, R] Now consider that each data point represented in vector form can be represented as a
p  p matrix for a suitable p. Using this transformed train data, build a convolution neural
network (CNN) with 3 convolution cum max-pool blocks (where max-pool follows a convolu-
tion operation) followed by a fully connected layer and an output layer. You are free to choose
the kernel size, stride and padding in each convolution operation. Also use a max-pool layer
of appropriate grid size in each layer. Use a soft-max at the output layer and a cross-entropy
loss function to perform classification. Describe the CNN architecture you have used. Using the
CNN model, report the accuracy, precision, recall, F1 score for the train set and test set.

In [17]:
#Imort the required libraries
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
from keras.utils.np_utils import to_categorical
from sklearn.metrics import  classification_report , confusion_matrix , accuracy_score

import matplotlib.pyplot as plt
import pandas as pd #the pandas library is useful for data processing 
import numpy as np
import random
import time

In [18]:
#Get the data from the csv file 
sample_data_cnn = pd.read_csv('https://github.com/arvind-maurya/MachineLearning/blob/master/Assignment/Q3/Q3_data.csv?raw=true', index_col=False)
#print the data 
sample_data_cnn

label  feature0  feature1  ...  feature781  feature782  feature783
0          1         0         0  ...           0           0           0
1          2         0         0  ...           0           0           0
2          3         0         0  ...           0           0           0
3          4         0         0  ...           0           0           0
4          1         0         0  ...           0           0           0
...      ...       ...       ...  ...         ...         ...         ...
23995      4         0         0  ...           0           0           0
23996      1         0         0  ...           0           0           0
23997      2         0         0  ...           0           0           0
23998      3         0         0  ...           0           0           0
23999      4         0         0  ...           0           0           0

[24000 rows x 785 columns]

In [19]:
#Separate the feature and target column
y_cnn = sample_data_cnn.pop('label')
X_cnn = sample_data_cnn
X_cnn = X_cnn.to_numpy()
y_cnn = y_cnn.to_numpy()
print(X_cnn)
print(y_cnn)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[1 2 3 ... 2 3 4]


In [20]:
#We will use the sklearn train_test_split which shuffle and break the data ins required ratio
from sklearn.model_selection import train_test_split
# split into train test sets
X_train_cnn, X_test_cnn, y_train_cnn, y_test_cnn = train_test_split(X_cnn,y_cnn, test_size=0.2)
X_train_cnn = X_train_cnn/255
X_test_cnn = X_test_cnn/255
print('Train data feature: ', X_train_cnn)
print('Train data Label: ', y_train_cnn)
print('Test data feature: ', X_test_cnn)
print('Test data Label: ',y_test_cnn)

Train data feature:  [[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
Train data Label:  [3 2 3 ... 3 1 3]
Test data feature:  [[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
Test data Label:  [3 2 4 ... 4 3 2]


In [21]:
print('Shape of Train data feature: ', X_train_cnn.shape)
print('Shape of Train data Label: ', y_train_cnn.shape)
print('Shape of Test data feature: ', X_test_cnn.shape)
print('Shape of Test data Label: ',y_test_cnn.shape)

Shape of Train data feature:  (19200, 784)
Shape of Train data Label:  (19200,)
Shape of Test data feature:  (4800, 784)
Shape of Test data Label:  (4800,)


In [22]:
#Get the unique lable from train and test feature and see if we dont have class imbalance in train and test data
unique, counts = np.unique(y_train_cnn, return_counts=True)
print('Train label:\n', np.asarray((unique, counts)).T)
unique, counts = np.unique(y_test_cnn, return_counts=True)
print('Test Label:\n',np.asarray((unique, counts)).T)

Train label:
 [[   1 4835]
 [   2 4832]
 [   3 4761]
 [   4 4772]]
Test Label:
 [[   1 1165]
 [   2 1168]
 [   3 1239]
 [   4 1228]]


In [23]:
#rehaping the images into equal dim.
X_train_cnn = X_train_cnn.reshape(len(X_train_cnn),28,28,1)
X_test_cnn = X_test_cnn.reshape(len(X_test_cnn),28,28,1)

In [24]:
from keras.utils.np_utils import to_categorical
#one-hot encode target column
y_train_cnn = to_categorical(y_train_cnn)
y_test_cnn = to_categorical(y_test_cnn)
y_train_cnn[0]

array([0., 0., 0., 1., 0.], dtype=float32)

In [25]:
#create model
model_cnn = keras.Sequential()
#add model layers
model_cnn.add(layers.Conv2D(64, kernel_size=3, activation='relu', input_shape=(28,28,1)))
model_cnn.add(layers.Conv2D(32, kernel_size=3, activation='relu'))
model_cnn.add(layers.Conv2D(16, kernel_size=3, activation='relu'))
model_cnn.add(layers.MaxPooling2D(pool_size=2))
model_cnn.add(layers.Flatten())
model_cnn.add(layers.Dense(5, activation='softmax'))

In [26]:
#compile model using accuracy to measure model performance
model_cnn.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])


In [27]:
#train the model
model_cnn.fit(X_train_cnn, y_train_cnn, validation_data=(X_test_cnn, y_test_cnn), epochs=3)

Epoch 1/3
600/600 [==============================] - 64s 106ms/step - loss: 0.1315 - accuracy: 0.9561 - val_loss: 0.0640 - val_accuracy: 0.9808
Epoch 2/3
600/600 [==============================] - 64s 107ms/step - loss: 0.0407 - accuracy: 0.9870 - val_loss: 0.0507 - val_accuracy: 0.9854
Epoch 3/3
600/600 [==============================] - 64s 107ms/step - loss: 0.0289 - accuracy: 0.9902 - val_loss: 0.0474 - val_accuracy: 0.9867


In [28]:
#predict first 4 images in the test set
model_cnn.predict(X_test_cnn[:4])

array([[1.1110682e-11, 5.5161244e-08, 8.6393994e-09, 9.9999988e-01,
        6.2997461e-11],
       [7.3738164e-08, 2.4083474e-06, 9.8908079e-01, 9.1387117e-03,
        1.7780681e-03],
       [2.6007372e-11, 1.0032370e-09, 9.9690989e-10, 4.5425500e-07,
        9.9999952e-01],
       [1.2894112e-08, 2.0394017e-07, 9.7209293e-01, 5.7420466e-04,
        2.7332643e-02]], dtype=float32)

The above give the probability for prediction for classes. We should take the value which has higher probability 

In [29]:
#actual results for first 4 images in test set
y_test_cnn[:4]

array([[0., 0., 0., 1., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 1., 0., 0.]], dtype=float32)

Same  is matching with the test data output of test data.