<a href="https://colab.research.google.com/github/arvind-maurya/MachineLearning/blob/master/Assignment/AIMLCEP_Q3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [102]:
#First, we import the required packages
import torch
import numpy as np
import pandas as pd #the pandas library is useful for data processing 
import matplotlib.pyplot as plt #the matplotlib library is useful for plotting purposes


## **Q3.a Shuffle and break the data into 80% train and 20% test data**

In [103]:


#Get the data from the csv file 
sample_data = pd.read_csv('https://github.com/arvind-maurya/MachineLearning/blob/master/Assignment/Q3/Q3_data.csv?raw=true', index_col=False)


#print the data 
sample_data

label  feature0  feature1  ...  feature781  feature782  feature783
0          1         0         0  ...           0           0           0
1          2         0         0  ...           0           0           0
2          3         0         0  ...           0           0           0
3          4         0         0  ...           0           0           0
4          1         0         0  ...           0           0           0
...      ...       ...       ...  ...         ...         ...         ...
23995      4         0         0  ...           0           0           0
23996      1         0         0  ...           0           0           0
23997      2         0         0  ...           0           0           0
23998      3         0         0  ...           0           0           0
23999      4         0         0  ...           0           0           0

[24000 rows x 785 columns]

In [104]:
#Separate the feature and target column
y = sample_data.pop('label')
X = sample_data
print(X)
print(y)

       feature0  feature1  feature2  ...  feature781  feature782  feature783
0             0         0         0  ...           0           0           0
1             0         0         0  ...           0           0           0
2             0         0         0  ...           0           0           0
3             0         0         0  ...           0           0           0
4             0         0         0  ...           0           0           0
...         ...       ...       ...  ...         ...         ...         ...
23995         0         0         0  ...           0           0           0
23996         0         0         0  ...           0           0           0
23997         0         0         0  ...           0           0           0
23998         0         0         0  ...           0           0           0
23999         0         0         0  ...           0           0           0

[24000 rows x 784 columns]
0        1
1        2
2        3
3        4
4   

In [105]:
#We will use the sklearn train_test_split which shuffle and break the data ins required ratio
from sklearn.model_selection import train_test_split
# split into train test sets
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.2)
print('Train data feature: ', X_train)
print('Train data Label: ', y_train)
print('Test data feature: ', X_test)
print('Test data Label: ',y_test)

Train data feature:         feature0  feature1  feature2  ...  feature781  feature782  feature783
20211         0         0         0  ...           0           0           0
2869          0         0         0  ...           0           0           0
17371         0         0         0  ...           0           0           0
12387         0         0         0  ...           0           0           0
19158         0         0         0  ...           0           0           0
...         ...       ...       ...  ...         ...         ...         ...
7062          0         0         0  ...           0           0           0
6186          0         0         0  ...           0           0           0
7614          0         0         0  ...           0           0           0
18565         0         0         0  ...           0           0           0
22678         0         0         0  ...           0           0           0

[19200 rows x 784 columns]
Train data Label:  20211   

In [106]:
print('Shape of Train data feature: ', X_train.shape)
print('Shape of Train data Label: ', y_train.shape)
print('Shape of Test data feature: ', X_test.shape)
print('Shape of Test data Label: ',y_test.shape)

Shape of Train data feature:  (19200, 784)
Shape of Train data Label:  (19200,)
Shape of Test data feature:  (4800, 784)
Shape of Test data Label:  (4800,)


In [107]:
#Get the unique lable from train and test feature and see if we dont have class imbalance in train and test data
unique, counts = np.unique(y_train, return_counts=True)
print('Train label:\n', np.asarray((unique, counts)).T)
unique, counts = np.unique(y_test, return_counts=True)
print('Test Label:\n',np.asarray((unique, counts)).T)

Train label:
 [[   1 4803]
 [   2 4791]
 [   3 4773]
 [   4 4833]]
Test Label:
 [[   1 1197]
 [   2 1209]
 [   3 1227]
 [   4 1167]]


In [108]:
# from sklearn import preprocessing
# from keras.models import sequential #forward Propogation
# from keras.layers import Dense , Dropout, BatchNormalization #Dense is used for creating hidden and input layers
# from keras import optimizers # for back propogation
# #converting y response variable into categorical.
# from keras.utils.np_utils import to_categorical

import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
from keras.utils.np_utils import to_categorical
from sklearn.metrics import  classification_report , confusion_matrix , accuracy_score

In [109]:
!pip show keras

Name: keras
Version: 2.7.0
Summary: Deep learning for humans.
Home-page: https://keras.io/
Author: Keras team
Author-email: keras-users@googlegroups.com
License: Apache 2.0
Location: /usr/local/lib/python3.7/dist-packages
Requires: 
Required-by: tensorflow, keras-vis


In [110]:
#Convert the label data into categorical data
y_train = to_categorical(y_train)
y_test = to_categorical(y_test)


In [111]:
print('Shape of Train data feature: ', X_train.shape)
print('Shape of Train data Label: ', y_train.shape)
print('Shape of Test data feature: ', X_test.shape)
print('Shape of Test data Label: ',y_test.shape)
#Looking at the shape , we have 784 input and 5 output.


Shape of Train data feature:  (19200, 784)
Shape of Train data Label:  (19200, 5)
Shape of Test data feature:  (4800, 784)
Shape of Test data Label:  (4800, 5)


In [112]:
#Create NN layers now
model = keras.Sequential()
model.add(Dense(5,input_dim=784,activation='relu')) #i/p Layer
model.add(Dense(5,input_dim=5,activation='relu')) # hidden layer1
model.add(Dense(5,input_dim=5,activation='relu')) # hidden layer2
model.add(Dense(5,input_dim=5,activation='relu')) # hidden layer3
model.add(Dense(5,activation='softmax')) #output layer



In [113]:
print(len(model.layers))  # 2

3


In [114]:
#optimizer
adam = keras.optimizers.Adam(learning_rate = 0.01)
model.compile(optimizer=adam, loss='categorical_crossentropy', metrics=['accuracy'])

In [115]:
#forward and back ward propogration
model.fit(X_train, y_train, batch_size=80, epochs=100)

Epoch 1/100
240/240 [==============================] - 1s 3ms/step - loss: 1.3386 - accuracy: 0.4736
Epoch 2/100
240/240 [==============================] - 1s 3ms/step - loss: 0.8918 - accuracy: 0.4888
Epoch 3/100
240/240 [==============================] - 1s 3ms/step - loss: 0.8741 - accuracy: 0.4941
Epoch 4/100
240/240 [==============================] - 1s 3ms/step - loss: 0.8638 - accuracy: 0.4963
Epoch 5/100
240/240 [==============================] - 1s 3ms/step - loss: 0.8627 - accuracy: 0.4907
Epoch 6/100
240/240 [==============================] - 1s 3ms/step - loss: 0.9163 - accuracy: 0.4889
Epoch 7/100
240/240 [==============================] - 1s 3ms/step - loss: 0.8984 - accuracy: 0.4889
Epoch 8/100
240/240 [==============================] - 1s 3ms/step - loss: 0.8893 - accuracy: 0.4877
Epoch 9/100
240/240 [==============================] - 1s 3ms/step - loss: 0.8899 - accuracy: 0.4870
Epoch 10/100
240/240 [==============================] - 1s 3ms/step - loss: 0.8732 - accura

In [116]:
#predicted values
y_train_predict = model.predict(X_train)
y_train_predict

array([[0.00000000e+00, 0.00000000e+00, 5.57458857e-10, 0.00000000e+00,
        1.00000000e+00],
       [0.00000000e+00, 5.42602421e-13, 8.25889766e-01, 1.58544824e-01,
        1.55654596e-02],
       [0.00000000e+00, 0.00000000e+00, 1.06023385e-10, 0.00000000e+00,
        1.00000000e+00],
       ...,
       [0.00000000e+00, 4.16249975e-07, 2.74619341e-01, 7.23285496e-01,
        2.09480082e-03],
       [0.00000000e+00, 1.87036910e-08, 4.14066792e-01, 5.82009673e-01,
        3.92352371e-03],
       [0.00000000e+00, 1.19483788e-02, 4.08351272e-02, 9.47069585e-01,
        1.46937280e-04]], dtype=float32)

In [117]:
y_test_predict = model.predict(X_test)
y_test_predict

array([[0.0000000e+00, 2.5106570e-14, 8.8308656e-01, 9.6709475e-02,
        2.0203972e-02],
       [0.0000000e+00, 1.2213609e-07, 3.2692173e-01, 6.7035919e-01,
        2.7189706e-03],
       [0.0000000e+00, 1.3405861e-06, 2.2939563e-01, 7.6899308e-01,
        1.6099574e-03],
       ...,
       [0.0000000e+00, 1.5252025e-02, 3.8666178e-02, 9.4594520e-01,
        1.3659074e-04],
       [0.0000000e+00, 2.2374103e-08, 4.0549237e-01, 5.9071249e-01,
        3.7951008e-03],
       [0.0000000e+00, 2.6695561e-01, 1.4828608e-02, 7.1817440e-01,
        4.1376090e-05]], dtype=float32)

## **===========================================================**

## **Q3.b Train a multi-layer perceptron (MLP)**

Q3.b : [C, R] Use the train partition to train a multi-layer perceptron (MLP) with an input layer, 3
hidden layers and an output layer. You are free to choose the number of neurons and their ac-
tivation functions in the hidden layers. Use a soft-max at the output layer and a cross-entropy
loss function to perform classifcation. Describe the MLP architecture you have used. Using the
MLP model, report the accuracy, precision, recall, F1 score for the train set and test set.

In [118]:
# Import MLPClassifer 
from sklearn.neural_network import MLPClassifier

# Create model object
clf = MLPClassifier(hidden_layer_sizes=(3,3),
                    random_state=5,
                    verbose=True,
                    learning_rate_init=0.01)

# Fit data onto the model
clf.fit(X_train,y_train)

Iteration 1, loss = 2.94055473
Iteration 2, loss = 2.26659408
Iteration 3, loss = 2.25506352
Iteration 4, loss = 2.25272556
Iteration 5, loss = 2.25190330
Iteration 6, loss = 2.25118619
Iteration 7, loss = 2.25105308
Iteration 8, loss = 2.25093295
Iteration 9, loss = 2.25072669
Iteration 10, loss = 2.25030050
Iteration 11, loss = 2.25096568
Iteration 12, loss = 2.25082049
Iteration 13, loss = 2.25059912
Iteration 14, loss = 2.25040124
Iteration 15, loss = 2.25129013
Iteration 16, loss = 2.25053322
Iteration 17, loss = 2.25093029
Iteration 18, loss = 2.25050269
Iteration 19, loss = 2.25033661
Iteration 20, loss = 2.25038329
Iteration 21, loss = 2.25042288
Training loss did not improve more than tol=0.000100 for 10 consecutive epochs. Stopping.


MLPClassifier(hidden_layer_sizes=(3, 3), learning_rate_init=0.01,
              random_state=5, verbose=True)

In [119]:
# Make prediction on test dataset
ypred=clf.predict(X_test)

# Import accuracy score 
from sklearn.metrics import accuracy_score

# Calcuate accuracy
accuracy_score(y_test,ypred)

0.0

##Creating datasets for multi-class Classification:

##Multi-class Classification Problem

In [129]:
# how many samples per batch to load
batch_size = 20

# convert data to torch.FloatTensor
transform = transforms.ToTensor()



In [130]:
# prepare data loaders
train_loader_multi = torch.utils.data.DataLoader(train_data, batch_size=batch_size)
test_loader_multi = torch.utils.data.DataLoader(test_data, batch_size=batch_size)

In [131]:
## Define the NN architecture
import torch.nn as nn

class MLP_multi(nn.Module):
    def __init__(self):
        super(MLP_multi, self).__init__()
        self.fc1 = nn.Linear(28 * 28, 512)
        # linear layer (n_hidden -> hidden_2)
        self.fc2 = nn.Linear(512, 512)
        # linear layer (n_hidden -> 1)
        self.fc3 = nn.Linear(512, 10)

    def forward(self, x):
        # flatten image input
        x = x.view(-1, 28 * 28)
        # add hidden layer, with relu activation function
        x = torch.relu(self.fc1(x))
        x = torch.relu(self.fc2(x))
        x = self.fc3(x)
        return x

# initialize the MLP
model_multi = MLP_multi()
print(model_multi)

MLP_multi(
  (fc1): Linear(in_features=784, out_features=512, bias=True)
  (fc2): Linear(in_features=512, out_features=512, bias=True)
  (fc3): Linear(in_features=512, out_features=10, bias=True)
)


In [132]:
## Specify loss and optimization functions

# specify loss function
criterion_multi = nn.CrossEntropyLoss()

# specify optimizer
optimizer = torch.optim.SGD(model_multi.parameters(), lr=0.001)

In [ ]:
# number of epochs to train the model
n_epochs = 200

model_multi.train() # prep model for training
errors = np.zeros(n_epochs)
for epoch in range(n_epochs):
    train_loss = 0.0
    # train the model
    for data, target in train_loader_multi:
        # clear the gradients of all optimized variables
        optimizer.zero_grad()
        # forward pass: compute predicted outputs by passing inputs to the model
        output = model_multi(data)
        # calculate the loss
        loss_multi = criterion_multi(output, target)
        # backward pass: compute gradient of the loss with respect to model parameters
        loss_multi.backward()
        # perform the optimization step (parameter update)
        optimizer.step()
        # update running training loss
        train_loss += loss_multi.item()*data.size(0)
        
    # print training statistics 
    # calculate average loss over an epoch
    train_loss = train_loss/len(train_loader_multi.dataset)
    errors[epoch] = train_loss
    if (epoch+1)%10 == 0:
      print('Epoch: {} \tTraining Loss: {:.6f}'.format(epoch+1, train_loss))

Epoch: 10 	Training Loss: 1.533784
Epoch: 20 	Training Loss: 1.320631


In [ ]:
x = np.arange(1, len(errors)+1)
plt.plot(x, errors, label="Loss on Train set")
plt.legend()
plt.title('CE - Learning Rate = 0.001')
plt.xlabel("Epoch")
plt.ylabel("Loss")
plt.show()

In [ ]:
test_loss = 0.0
class_correct = list(0. for i in range(10))
class_total = list(0. for i in range(10))

model_multi.eval() # prep model for *evaluation*

for data, target in test_loader_multi:
    # forward pass: compute predicted outputs by passing inputs to the model
    output = model_multi(data)
    output = output.squeeze()
    # calculate the loss
    loss = criterion_multi(output, target)
    # update test loss 
    test_loss += loss.item()*data.size(0)
    # convert output probabilities to predicted class
    _, pred = torch.max(output, 1)
    # compare predictions to true label
    correct = np.squeeze(pred.eq(target.data.view_as(pred)))
    # calculate test accuracy for each object class
    for i in range(batch_size):
        label = target.data[i]
        class_correct[label] += correct[i].item()
        class_total[label] += 1

# calculate and print avg test loss
test_loss = test_loss/len(test_loader_multi.dataset)
print('Test Loss: {:.6f}\n'.format(test_loss))

for i in range(10):
    if class_total[i] > 0:
        print('Test Accuracy of %5s: %2d%% (%2d/%2d)' % (str(i), 100 * class_correct[i] / class_total[i], np.sum(class_correct[i]), np.sum(class_total[i])))
    else:
        print('Test Accuracy of %5s: N/A (no training examples)' % str(i))

print('\nTest Accuracy (Overall): %2d%% (%2d/%2d)' % (100. * np.sum(class_correct) / np.sum(class_total), np.sum(class_correct), np.sum(class_total)))